/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HandoverRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_REWARD"
      | "CLAIM_EXPIRY"
      | "MAX_STRING_LEN"
      | "acceptAdmin"
      | "admin"
      | "approveClaim"
      | "calculateReward"
      | "claims"
      | "completeClaim"
      | "expireClaim"
      | "finderClaimCount"
      | "getClaim"
      | "getClaimKey"
      | "initiateClaim"
      | "pendingAdmin"
      | "rejectClaim"
      | "rewardToken"
      | "setAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminTransferAccepted"
      | "AdminTransferInitiated"
      | "ClaimApproved"
      | "ClaimCompleted"
      | "ClaimExpired"
      | "ClaimInitiated"
      | "ClaimRejected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CLAIM_EXPIRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_STRING_LEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approveClaim",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "claims", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "completeClaim",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "expireClaim",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finderClaimCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getClaim", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getClaimKey",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateClaim",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rejectClaim",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CLAIM_EXPIRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_STRING_LEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claims", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expireClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finderClaimCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getClaimKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
}

export namespace AdminTransferAcceptedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminTransferInitiatedEvent {
  export type InputTuple = [
    currentAdmin: AddressLike,
    pendingAdmin: AddressLike
  ];
  export type OutputTuple = [currentAdmin: string, pendingAdmin: string];
  export interface OutputObject {
    currentAdmin: string;
    pendingAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimApprovedEvent {
  export type InputTuple = [
    internalKey: BytesLike,
    claimId: string,
    approvedBy: AddressLike
  ];
  export type OutputTuple = [
    internalKey: string,
    claimId: string,
    approvedBy: string
  ];
  export interface OutputObject {
    internalKey: string;
    claimId: string;
    approvedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimCompletedEvent {
  export type InputTuple = [
    internalKey: BytesLike,
    claimId: string,
    itemId: string,
    owner: AddressLike,
    finder: AddressLike,
    rewardAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    internalKey: string,
    claimId: string,
    itemId: string,
    owner: string,
    finder: string,
    rewardAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    internalKey: string;
    claimId: string;
    itemId: string;
    owner: string;
    finder: string;
    rewardAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimExpiredEvent {
  export type InputTuple = [
    internalKey: BytesLike,
    claimId: string,
    expiredAt: BigNumberish
  ];
  export type OutputTuple = [
    internalKey: string,
    claimId: string,
    expiredAt: bigint
  ];
  export interface OutputObject {
    internalKey: string;
    claimId: string;
    expiredAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimInitiatedEvent {
  export type InputTuple = [
    internalKey: BytesLike,
    claimId: string,
    itemId: string,
    owner: AddressLike,
    secretHash: BytesLike,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    internalKey: string,
    claimId: string,
    itemId: string,
    owner: string,
    secretHash: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    internalKey: string;
    claimId: string;
    itemId: string;
    owner: string;
    secretHash: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimRejectedEvent {
  export type InputTuple = [
    internalKey: BytesLike,
    claimId: string,
    rejectedBy: AddressLike
  ];
  export type OutputTuple = [
    internalKey: string,
    claimId: string,
    rejectedBy: string
  ];
  export interface OutputObject {
    internalKey: string;
    claimId: string;
    rejectedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HandoverRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): HandoverRegistry;
  waitForDeployment(): Promise<this>;

  interface: HandoverRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_REWARD: TypedContractMethod<[], [bigint], "view">;

  CLAIM_EXPIRY: TypedContractMethod<[], [bigint], "view">;

  MAX_STRING_LEN: TypedContractMethod<[], [bigint], "view">;

  acceptAdmin: TypedContractMethod<[], [void], "nonpayable">;

  admin: TypedContractMethod<[], [string], "view">;

  approveClaim: TypedContractMethod<
    [internalKey: BytesLike],
    [void],
    "nonpayable"
  >;

  calculateReward: TypedContractMethod<[finder: AddressLike], [bigint], "view">;

  claims: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        claimId: string;
        itemId: string;
        owner: string;
        finder: string;
        secretHash: string;
        status: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        rewardAmount: bigint;
      }
    ],
    "view"
  >;

  completeClaim: TypedContractMethod<
    [internalKey: BytesLike, secretHashProof: BytesLike],
    [void],
    "nonpayable"
  >;

  expireClaim: TypedContractMethod<
    [internalKey: BytesLike],
    [void],
    "nonpayable"
  >;

  finderClaimCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getClaim: TypedContractMethod<
    [internalKey: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint, bigint] & {
        claimId: string;
        itemId: string;
        owner: string;
        finder: string;
        status: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        rewardAmount: bigint;
      }
    ],
    "view"
  >;

  getClaimKey: TypedContractMethod<
    [claimId: string, owner: AddressLike],
    [string],
    "view"
  >;

  initiateClaim: TypedContractMethod<
    [claimId: string, itemId: string, secretHash: BytesLike],
    [void],
    "nonpayable"
  >;

  pendingAdmin: TypedContractMethod<[], [string], "view">;

  rejectClaim: TypedContractMethod<
    [internalKey: BytesLike],
    [void],
    "nonpayable"
  >;

  rewardToken: TypedContractMethod<[], [string], "view">;

  setAdmin: TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CLAIM_EXPIRY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_STRING_LEN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptAdmin"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveClaim"
  ): TypedContractMethod<[internalKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateReward"
  ): TypedContractMethod<[finder: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "claims"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        claimId: string;
        itemId: string;
        owner: string;
        finder: string;
        secretHash: string;
        status: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        rewardAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "completeClaim"
  ): TypedContractMethod<
    [internalKey: BytesLike, secretHashProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "expireClaim"
  ): TypedContractMethod<[internalKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finderClaimCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getClaim"
  ): TypedContractMethod<
    [internalKey: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint, bigint] & {
        claimId: string;
        itemId: string;
        owner: string;
        finder: string;
        status: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        rewardAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaimKey"
  ): TypedContractMethod<
    [claimId: string, owner: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateClaim"
  ): TypedContractMethod<
    [claimId: string, itemId: string, secretHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pendingAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rejectClaim"
  ): TypedContractMethod<[internalKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AdminTransferAccepted"
  ): TypedContractEvent<
    AdminTransferAcceptedEvent.InputTuple,
    AdminTransferAcceptedEvent.OutputTuple,
    AdminTransferAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "AdminTransferInitiated"
  ): TypedContractEvent<
    AdminTransferInitiatedEvent.InputTuple,
    AdminTransferInitiatedEvent.OutputTuple,
    AdminTransferInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimApproved"
  ): TypedContractEvent<
    ClaimApprovedEvent.InputTuple,
    ClaimApprovedEvent.OutputTuple,
    ClaimApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimCompleted"
  ): TypedContractEvent<
    ClaimCompletedEvent.InputTuple,
    ClaimCompletedEvent.OutputTuple,
    ClaimCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimExpired"
  ): TypedContractEvent<
    ClaimExpiredEvent.InputTuple,
    ClaimExpiredEvent.OutputTuple,
    ClaimExpiredEvent.OutputObject
  >;
  getEvent(
    key: "ClaimInitiated"
  ): TypedContractEvent<
    ClaimInitiatedEvent.InputTuple,
    ClaimInitiatedEvent.OutputTuple,
    ClaimInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimRejected"
  ): TypedContractEvent<
    ClaimRejectedEvent.InputTuple,
    ClaimRejectedEvent.OutputTuple,
    ClaimRejectedEvent.OutputObject
  >;

  filters: {
    "AdminTransferAccepted(address,address)": TypedContractEvent<
      AdminTransferAcceptedEvent.InputTuple,
      AdminTransferAcceptedEvent.OutputTuple,
      AdminTransferAcceptedEvent.OutputObject
    >;
    AdminTransferAccepted: TypedContractEvent<
      AdminTransferAcceptedEvent.InputTuple,
      AdminTransferAcceptedEvent.OutputTuple,
      AdminTransferAcceptedEvent.OutputObject
    >;

    "AdminTransferInitiated(address,address)": TypedContractEvent<
      AdminTransferInitiatedEvent.InputTuple,
      AdminTransferInitiatedEvent.OutputTuple,
      AdminTransferInitiatedEvent.OutputObject
    >;
    AdminTransferInitiated: TypedContractEvent<
      AdminTransferInitiatedEvent.InputTuple,
      AdminTransferInitiatedEvent.OutputTuple,
      AdminTransferInitiatedEvent.OutputObject
    >;

    "ClaimApproved(bytes32,string,address)": TypedContractEvent<
      ClaimApprovedEvent.InputTuple,
      ClaimApprovedEvent.OutputTuple,
      ClaimApprovedEvent.OutputObject
    >;
    ClaimApproved: TypedContractEvent<
      ClaimApprovedEvent.InputTuple,
      ClaimApprovedEvent.OutputTuple,
      ClaimApprovedEvent.OutputObject
    >;

    "ClaimCompleted(bytes32,string,string,address,address,uint256,uint256)": TypedContractEvent<
      ClaimCompletedEvent.InputTuple,
      ClaimCompletedEvent.OutputTuple,
      ClaimCompletedEvent.OutputObject
    >;
    ClaimCompleted: TypedContractEvent<
      ClaimCompletedEvent.InputTuple,
      ClaimCompletedEvent.OutputTuple,
      ClaimCompletedEvent.OutputObject
    >;

    "ClaimExpired(bytes32,string,uint256)": TypedContractEvent<
      ClaimExpiredEvent.InputTuple,
      ClaimExpiredEvent.OutputTuple,
      ClaimExpiredEvent.OutputObject
    >;
    ClaimExpired: TypedContractEvent<
      ClaimExpiredEvent.InputTuple,
      ClaimExpiredEvent.OutputTuple,
      ClaimExpiredEvent.OutputObject
    >;

    "ClaimInitiated(bytes32,string,string,address,bytes32,uint256)": TypedContractEvent<
      ClaimInitiatedEvent.InputTuple,
      ClaimInitiatedEvent.OutputTuple,
      ClaimInitiatedEvent.OutputObject
    >;
    ClaimInitiated: TypedContractEvent<
      ClaimInitiatedEvent.InputTuple,
      ClaimInitiatedEvent.OutputTuple,
      ClaimInitiatedEvent.OutputObject
    >;

    "ClaimRejected(bytes32,string,address)": TypedContractEvent<
      ClaimRejectedEvent.InputTuple,
      ClaimRejectedEvent.OutputTuple,
      ClaimRejectedEvent.OutputObject
    >;
    ClaimRejected: TypedContractEvent<
      ClaimRejectedEvent.InputTuple,
      ClaimRejectedEvent.OutputTuple,
      ClaimRejectedEvent.OutputObject
    >;
  };
}
