/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface HandoverRegistryInterface extends Interface {
  getFunction(nameOrSignature: "recordHandover"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "HandoverRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "recordHandover",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "recordHandover",
    data: BytesLike
  ): Result;
}

export namespace HandoverRecordedEvent {
  export type InputTuple = [
    claimId: string,
    itemId: string,
    claimantId: string,
    recordedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    claimId: string,
    itemId: string,
    claimantId: string,
    recordedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    claimId: string;
    itemId: string;
    claimantId: string;
    recordedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HandoverRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): HandoverRegistry;
  waitForDeployment(): Promise<this>;

  interface: HandoverRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  recordHandover: TypedContractMethod<
    [claimId: string, itemId: string, claimantId: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "recordHandover"
  ): TypedContractMethod<
    [claimId: string, itemId: string, claimantId: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "HandoverRecorded"
  ): TypedContractEvent<
    HandoverRecordedEvent.InputTuple,
    HandoverRecordedEvent.OutputTuple,
    HandoverRecordedEvent.OutputObject
  >;

  filters: {
    "HandoverRecorded(string,string,string,address,uint256)": TypedContractEvent<
      HandoverRecordedEvent.InputTuple,
      HandoverRecordedEvent.OutputTuple,
      HandoverRecordedEvent.OutputObject
    >;
    HandoverRecorded: TypedContractEvent<
      HandoverRecordedEvent.InputTuple,
      HandoverRecordedEvent.OutputTuple,
      HandoverRecordedEvent.OutputObject
    >;
  };
}
