/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HandoverRegistry } from "./HandoverRegistry";
export * as factories from "./factories";
export { HandoverRegistry__factory } from "./factories/HandoverRegistry__factory";
